set(_CATKIN_CURRENT_PACKAGE "raven2_moveit_config")
set(raven2_moveit_config_VERSION "0.3.0")
set(raven2_moveit_config_MAINTAINER "Robert P. <rtp4qg@virginia.edu>")
set(raven2_moveit_config_PACKAGE_FORMAT "1")
set(raven2_moveit_config_BUILD_DEPENDS "raven_visualization")
set(raven2_moveit_config_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "raven_visualization")
set(raven2_moveit_config_BUILDTOOL_DEPENDS "catkin")
set(raven2_moveit_config_BUILDTOOL_EXPORT_DEPENDS )
set(raven2_moveit_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "raven_visualization")
set(raven2_moveit_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "raven_visualization")
set(raven2_moveit_config_TEST_DEPENDS )
set(raven2_moveit_config_DOC_DEPENDS )
set(raven2_moveit_config_DEPRECATED "")